#!/bin/sh

set -u
set -e

# whether to delete a source file after successfully convertion
export CV_DELETE=0

# whether to not convert videos
export CV_DRY=0

# whether to only convert one video per directory
export CV_SINGLE=0

BASEDIR=$(dirname "$0")
PARENT_DIR="/Volumes/MEDIA/.raw"

# ===---------------------------------------------------------------------------------------------------------------===
#
#
# parse command line

while (( $# > 0 ))
do
   case ${1} in
   --trace                 ) set -x ;                                          shift  ;;
   --delete                ) export CV_DELETE=1 ;                              shift  ;;
   --dry                   ) export CV_DRY=1 ;                                 shift  ;;
   --single                ) export CV_SINGLE=1 ;                              shift  ;;
   *                       ) echo "Unknown argument: ${1}" ;                   exit 0 ;;
   esac
done

FINAL_MOM_DIR="${PARENT_DIR}/final-mov"
FINAL_MOM_LOW_DIR="${PARENT_DIR}/final-mov-low"
FINAL_MOV_THUMBNAILS="${PARENT_DIR}/final-mov-thumbnails"

mkdir -p "${FINAL_MOV_THUMBNAILS}"

/bin/sh "${BASEDIR}/scripts/convert-directory" \
   "${FINAL_MOM_DIR}" \
   "${FINAL_MOV_THUMBNAILS}" \
   "${BASEDIR}/scripts/thumbnail" \
   "mov" \
   "jpg"
