#!/bin/sh

if [ $# -ne 2 ] ; then
   echo "no arguments"
   exit 0
fi

INPUT_DIR="${1}"
if [ ! -d "${INPUT_DIR}" ] ; then
   echo "input file does not exist: ${INPUT_DIR}"
   exit 0
fi

OUTPUT_DIR="${2}"

echo "INPUT_DIR: ${INPUT_DIR}"
echo "OUTPUT_DIR: ${OUTPUT_DIR}"

mkdir -p "${OUTPUT_DIR}"


for FILE_NAME in $(ls "${INPUT_DIR}");
do
   if [ ${FILE_NAME: -4} == ".mp4" ]; then
      
      INPUT_FILE_PATH="${INPUT_DIR}/${FILE_NAME}"
      OUTPUT_FILE_PATH="${OUTPUT_DIR}/${FILE_NAME}.mov"

      echo "INPUT_FILE_PATH: ${INPUT_FILE_PATH}"
      echo "OUTPUT_FILE_PATH: ${OUTPUT_FILE_PATH}"

      if [ -f "${OUTPUT_FILE_PATH}" ]; then
         echo "skipping file because it already exist: ${OUTPUT_FILE_PATH}"
      else
         echo "convert file: ${INPUT_FILE_PATH}"

         /bin/sh /app/scripts/to-mov \
            "${INPUT_FILE_PATH}" \
            "${OUTPUT_FILE_PATH}"

         if [ $? -eq 0 ]; then
            echo "removing file: ${INPUT_FILE_PATH}"
            # rm -rf "${INPUT_FILE_PATH}"
         else
            echo "not removing file"
         fi 

         exit 0
      fi
   else
      echo "ignoring file: ${FILE_NAME}"
   fi
done

exit 0
