#!/bin/bash

if [ $# -nq 2 ] ; then
    echo "no arguments"
    exit 0
fi

INPUT_PATH="${1}"
if [ ! -f "${INPUT_PATH}" ] ; then
    echo "input file does not exist: ${INPUT_PATH}"
    exit 0
fi

OUTPUT_PATH="${2}"
if [ -f "${OUTPUT_PATH}" ] ; then
    echo "output file already existing: ${OUTPUT_PATH}"
    exit 0
fi

echo "INPUT_PATH: ${INPUT_PATH}"
echo "OUTPUT_PATH: ${OUTPUT_PATH}"

ffmpeg -y \
   -hide_banner \
   -i "${INPUT_PATH}" \
   -c:v mpeg4 \
   -c:a aac \
   -f mp4 \
   -b:v 4000k \
   -b:a 128k \
   -ac 2 \
   -mbd rd \
   -flags +mv4+aic \
   -trellis 2 \
   -cmp 2 \
   -subcmp 2 \
   -g 300 \
   -threads auto \
   -strict experimental \
   "${OUTPUT_PATH}"

# -loglevel warning \

exit 0
