#!/bin/sh

INPUT_PATH="${1}"
OUTPUT_PATH="${2}"

ffmpeg \
   -hide_banner \
   -i "${INPUT_PATH}" \
   -c:v libx264 \
   -preset slow \
   -profile:v high \
   -crf 18 \
   -coder 1 \
   -pix_fmt yuv420p \
   -movflags +faststart \
   -g 30 \
   -bf 2 \
   -c:a aac \
   -b:a 384k \
   -profile:a aac_low \
   -f mov \
   "${OUTPUT_PATH}"

# -vcodec copy \
# -acodec copy \
# -loglevel warning \
# -vcodec h264 \

exit 0
