#!/bin/bash

if [ $# -ne 2 ] ; then
   echo "no arguments"
   exit 0
fi

INPUT_DIR="${1}"
if [ ! -d "${INPUT_DIR}" ] ; then
   echo "input file does not exist: ${INPUT_DIR}"
   exit 0
fi

OUTPUT_DIR="${2}"

echo "INPUT_DIR: ${INPUT_DIR}"
echo "OUTPUT_DIR: ${OUTPUT_DIR}"

mkdir -p "${OUTPUT_DIR}"


for FILE_NAME in $(ls "${INPUT_DIR}");
do
   if [ ${FILE_NAME: -4} == ".mp4" ] || [ ${FILE_NAME: -4} == ".mov" ]; then
      
      INPUT_FILE_PATH="${INPUT_DIR}/${FILE_NAME}"
      OUTPUT_FILE_PATH="${OUTPUT_DIR}/${FILE_NAME}.mov"

      echo "INPUT_FILE_PATH: ${INPUT_FILE_PATH}"
      echo "OUTPUT_FILE_PATH: ${OUTPUT_FILE_PATH}"

      if [ -f "${OUTPUT_FILE_PATH}" ]; then
         echo "skippinf file because it already exist: ${OUTPUT_FILE_PATH}"
      else
         echo "convert file: ${INPUT_FILE_PATH}"

         MY_PATH="`dirname \"$0\"`"
         echo "MY_PATH: ${MY_PATH}"

         CONVERT_TOOL="${MY_PATH}/convert-high-to-low"
         ${CONVERT_TOOL} "${INPUT_FILE_PATH}" "${OUTPUT_FILE_PATH}"

	 exit 0
      fi
   else
      echo "ignoring file: ${FILE_NAME}"
   fi
done

exit 0
