#!/bin/bash

if [ $# -ne 5 ] ; then
  echo "no arguments" ; exit 0
fi

INPUT_DIR="${1}"
OUTPUT_DIR="${2}"
CONVERT_COM_PATH="${3}"
FILE_EXTENSION="${4}"
TARGET_FILE_EXTENSION="${5}"

if [ ! -d "${INPUT_DIR}" ] ; then
   echo "input file does not exist: ${INPUT_DIR}" ; exit 0
fi

echo "INPUT_DIR: ${INPUT_DIR}"
echo "OUTPUT_DIR: ${OUTPUT_DIR}"
echo "CONVERT_COM_PATH: ${CONVERT_COM_PATH}"
echo "FILE_EXTENSION: ${FILE_EXTENSION}"

echo "CV_DRY: ${CV_DRY}"
echo "CV_DELETE: ${CV_DELETE}"

mkdir -p "${OUTPUT_DIR}"
rm -rf "${INPUT_DIR}/.DS_Store"

if [ ! "$(ls -A ${INPUT_DIR})" ]; then
   echo "No files" ; exit 0
fi

for FILE_PATH in $INPUT_DIR/*.$FILE_EXTENSION ;
do
  FILE_NAME=$(basename -- "${FILE_PATH}")
  PURE_FILE_NAME="${FILE_NAME%.*}"
  OUTPUT_FILE_PATH="${OUTPUT_DIR}/${PURE_FILE_NAME}.${TARGET_FILE_EXTENSION}"
  INPUT_FILE_PATH="${FILE_PATH}"

  echo "OUTPUT_FILE_PATH: ${OUTPUT_FILE_PATH}"

  if [ -f "${OUTPUT_FILE_PATH}" ]; then
    echo "skipping file because it already exist: ${OUTPUT_FILE_PATH}"
  else
    echo "convert file: ${FILE_PATH}"
    if (( CV_DRY == 0 )) ; then
      /bin/sh "${CONVERT_COM_PATH}" \
        "${FILE_PATH}" \
        "${OUTPUT_FILE_PATH}"
    fi

    if (( CV_DELETE == 1 )) ; then
      echo "is CV_DELETE"
    fi

    if (( CV_SINGLE == 1 )) ; then
      exit 0
    fi
  fi
done

exit 0