#!/bin/bash

if [ $# -ne 2 ] ; then
    echo "no arguments"
    exit 0
fi

INPUT_PATH="${1}"
if [ ! -f "${INPUT_PATH}" ] ; then
    echo "input file does not exist: ${INPUT_PATH}"
    exit 0
fi

OUTPUT_PATH="${2}"
if [ -f "${OUTPUT_PATH}" ] ; then
    echo "output file already existing: ${OUTPUT_PATH}"
    exit 0
fi

echo "INPUT_PATH: ${INPUT_PATH}"
echo "OUTPUT_PATH: ${OUTPUT_PATH}"

ffmpeg \
   -hide_banner \
   -i "${INPUT_PATH}" \
   -f "mov" \
   -quality best \
   -codec:v libx264 \
   -pix_fmt yuv420p \
   -b:v 2500k \
   -minrate 1500k \
   -maxrate 4000k \
   -bufsize 5000k \
   -vf scale=-1:720 \
   "${OUTPUT_PATH}"

# -loglevel warning \

exit 0
