#!/bin/sh
echo "INPUT_PATH: ${1}"
echo "OUTPUT_PATH: ${2}"
ffmpeg \
   -hide_banner \
   -i "${1}" \
   -f mov \
   -quality best \
   -codec:v libx264 \
   -pix_fmt yuv420p \
   -b:v 2500k \
   -minrate 1500k \
   -maxrate 4000k \
   -bufsize 5000k \
   -vf scale=-1:720 \
   "${2}"
exit 0