#!/bin/sh

echo "INPUT_PATH: ${INPUT_PATH}"
echo "OUTPUT_PATH: ${OUTPUT_PATH}"

ffmpeg -y \
   -hide_banner \
   -i "${INPUT_PATH}" \
   -c:v mpeg4 \
   -c:a aac \
   -f mp4 \
   -b:v 4000k \
   -b:a 128k \
   -ac 2 \
   -mbd rd \
   -flags +mv4+aic \
   -trellis 2 \
   -cmp 2 \
   -subcmp 2 \
   -g 300 \
   -threads auto \
   -strict experimental \
   "${OUTPUT_PATH}"

# -loglevel warning \

exit 0
