#!/bin/sh
echo "INPUT_PATH: ${1}"
echo "OUTPUT_PATH: ${2}"
ffmpeg -y \
   -hide_banner \
   -i "${1}" \
   -c:v mpeg4 \
   -c:a aac \
   -f mp4 \
   -b:v 4000k \
   -b:a 128k \
   -ac 2 \
   -mbd rd \
   -flags +mv4+aic \
   -trellis 2 \
   -cmp 2 \
   -subcmp 2 \
   -g 300 \
   -threads auto \
   -strict experimental \
   "${2}"
exit 0