#!/bin/sh
echo "INPUT_PATH: ${1}"
echo "OUTPUT_PATH: ${2}"
ffmpeg \
   -hide_banner \
   -i "${1}" \
   -c:v libx264 \
   -preset slow \
   -profile:v high \
   -crf 18 \
   -coder 1 \
   -pix_fmt yuv420p \
   -movflags +faststart \
   -g 30 \
   -bf 2 \
   -c:a aac \
   -b:a 384k \
   -profile:a aac_low \
   -f mov \
   "${2}"

# -vcodec copy \
# -acodec copy \
# -loglevel warning \
# -vcodec h264 \

exit 0
